configure: check for libraries and programs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -34,12 +34,11 @@ check_installed() {
   [ "$?" -eq 127 ] && error "$1 command not installed / not found in \$PATH"
 }
 
-# parse_option() {
-#   res="$(echo "$1" | cut -f2 -d'=')"
-#   [ "$res" = "$1" ] && error "Option requires assignment '='  $1"
-#   [ "$res" = "${1}=" ] && error "Option requires assignment '='  $1"
-#   echo "$res"
-# }
+check_lib() {
+  echo "Checking for lib${1} (-l$1) ..."
+  echo 'int main(void){}' | "$CC" -xc - -l"$1" >/dev/null 2>&1 || error "Library 'lib${1}' not installed"
+  rm -f a.out
+}
 
 parse_option() {
   option="$1"
@@ -146,6 +145,13 @@ while :; do
   esac
   shift
 done
+
+check_installed "$CC"
+check_installed make
+check_lib sodium
+# check_lib z
+# check_lib curses
+# check_lib icu
 
 _features_list=""
 [ "$ascii_show_octal" = "1" ] && _features_list="${_features_list}ascii_show_octal  "
